abbr -a -- zr 'zoxide remove'
abbr -a -- cdqi 'zoxide query -i'
abbr -a -- zq 'zoxide query'
abbr -a -- cdq 'zoxide query'
abbr -a -- cda 'zoxide add'
abbr -a -- cdr 'zoxide remove'
abbr -a -- za 'zoxide add'
abbr -a -- zqi 'zoxide query -i'
abbr -a --position anywhere --function last_history_item -- !!
abbr -a -- zbr 'zig build run'
abbr -a -- zb 'zig build'
abbr -a -- cr 'cargo run'
abbr -a -- cb 'cargo build'
abbr -a -- gr 'go run '
abbr -a -- gm 'go mod tidy'
abbr -a -- fzfp "fzf --preview 'bat --color=always {}' --preview-window '~3'"
abbr -a -- jl 'jj log'
abbr -a -- jjbsr 'jj b s -r \'@-\''
abbr -a -- jjgpm 'jj git push main'
